#pragma once

#undef  ERR_SUCCESS
#define ERR_SUCCESS 					0
#define ERR_FAILURE						1
#define ERR_SSL_READ 					2
#define ERR_SSL_WRITE 					3
#define ERR_SSL_CONN 					4
#define ERR_SSL_CLIENT_CERT				5
#define ERR_SESS_INVALID				6
#define ERR_SESS_TIMEOUT				7
#define ERR_MEM_ALLOC					8
#define ERR_SOCK_CREATE					9
#define ERR_SOCK_ACCEPT					10
#define ERR_SOCK_RECV					11
#define ERR_SOCK_CLOSE					12
#define ERR_SOCK_BIND					13
#define ERR_SOCK_LISTEN					14
#define ERR_SOCK_SEND					15
#define ERR_SOCK_CONN					16
#define ERR_ITEM_NOT_FOUND				17
#define ERR_PARSE_COOKIE				18
#define ERR_HTTP_NOT_REDIR				19
#define ERR_HTTP_NO_LOCATION			20
#define ERR_CONTROL_SOCK_BIND			21
#define ERR_APP_CONN_LIMIT				22
#define ERR_BUF_SIZE					23
#define ERR_UNKNOWN_HOST				24
#define ERR_STILL_RUNNING				25
#define ERR_NOT_RUNNING					26
#define ERR_THREAD_JOIN					27
#define ERR_THREAD_CREATE				28
#define ERR_SOCK_SELECT					29
#define ERR_SERVER_CONFIG				30
#define ERR_SESS_SECOND_LOGIN			31
#define ERR_CERT_PASS					32
#define ERR_CERT_PARSE					33
#define ERR_CERT_FILE_READ				34
#define ERR_CTL_SOCK_CONN				35
#define ERR_CTL_SOCK_SEND				36
#define ERR_WRONG_USER_PASS				37
#define ERR_GET_AAA_METHOD				38
#define ERR_CONFIG_L3VPN				39
#define ERR_GET_L3VPN_CONFIG			40
#define ERR_INTERRUPTED					41
#define ERR_PARAM_INVALID               42
#define ERR_TUN_CREATE		            43
#define ERR_TUN_CONFIG		            44
#define ERR_SETUP_UDP					45
#define ERR_UDP_SEND					46
#define ERR_UDP_RECV					47
#define ERR_TUN_DOWN                    48
#define ERR_SERVER_AG                   49
#define ERR_SERVER_NO_RESP		        50
#define ERR_CLIENT_SECURITY		        51
#define ERR_CHOOSE_METHOD               52
#define ERR_UNSUPPORT_METHOD            53
#define ERR_SHUTDOWN_SOCKET             54
#define ERR_HTTP_PROXY_START_FAILED     55
#define ERR_SOCK_PROXY_START_FAILED     56
#define ERR_HTTP_PROXY_STOP_FAILED      57
#define ERR_SOCK_PROXY_STOP_FAILED      58
#define ERR_HTTP_SOCK_PROXY_STOP_FAILED 59
#define ERR_CALLBACK_FAILED             60
#define ERR_DEVID_APPROVE_PENDING       61
#define ERR_DEVID_APPROVE_DENY          62
#define ERR_DEVID_USER_LIMIT            63
#define ERR_DEVID_DEV_LIMIT             64
#define ERR_DEVID_UNREG	                65
#define ERR_CREATE_SESSION              66
#define ERR_CERT_NO                     67
#define ERR_CERT_INVALID_SIGNTURE       68
#define ERR_CERT_UNTRUSTED              69
#define ERR_CERT_EXPIRED                70
#define ERR_CERT_INVALID                71
#define ERR_CERT_REVOKED                72
#define ERR_CERT_SERVER_NO              73
#define ERR_CERT_SERVER_INVALID_SIGNTURE 74
#define ERR_CERT_SERVER_UNTRUSTED       75
#define ERR_CERT_SERVER_EXPIRED         76
#define ERR_CERT_SERVER_INVALID         77
#define ERR_CERT_SERVER_REVOKED         78
#define ERR_MAX                         79